title: An experiment was carried out
author: Matthew Plough
github_username: mplough
description: ""

markdown: kramdown
remote_theme: jekyll/minima
show_excerpts: false
plugins:
  - jekyll-feed

minima:
  skin: auto
